packages:
  - packages/*
  - scripts
  - tests
  - docs
  - content

ignoredBuiltDependencies:
  - opencv4nodejs-prebuilt

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - tesseract.js
  - unrs-resolver
  - vue-demi